apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW5AamZtZWRpYS5jb20= # Base64-encoded username (Replace 'user' with your actual username)
  POSTGRES_PASSWORD: TW9yZUNvbXBsZXhQYXNzd29yZDEh  # Base64-encoded password (Replace 'password' with your actual password)
