apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullName }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.fullName }}