apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  # values must be base64 encoded
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AamZtZWRpYS5jb20=
  PGADMIN_DEFAULT_PASSWORD: MTIzNA==